version: "2"
volumes:
  data-jenkins:
    driver: "local"
services:
  jenkins:
    image: "jenkins/jenkins:lts"
    ports:
      - "8080:8080"
    restart: "always"
    volumes:
      - "data-jenkins:/var/jenkins_home"
